### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Dsgnr-JM** [Moisesdemolf/lumina-alerts#2]
Muy buena idea amigo y las opciones estan excelentes, aunque falta mejorar mas el diseño.

**Comment by Moisesdemolf** [comment]
gracias bro, y si tienes razon le falta diseño y lo se pero se puede agregar eso e incluso hasta mas animaciones. 
Estate pendiente de las proximas mejoras

**Comment by Dsgnr-JM** [comment]
Claro hay muchas posibilidades y pues que sea agnóstico esta excelente, actualmente también ando trabajando en una librería de alertas llamada [BELL ALERT](https://belljs.vercel.app/)

**Comment by Dsgnr-JM** [comment]
La documentación esta excelente

**Comment by Moisesdemolf** [comment]
Ya vi esa librería y está bueno añadir una forma o formato así a mi
librería, aunque ya hay algo parecido pero le falta diseño.
Estarías dispuesto a probar una versión futura que sacaré de la
librería donde mejorare en muchos aspectos mi librería, ya que la opinión
de otra persona me ayuda a mi para hacer crecer la librería.
Pero desde ya gracias por tus opiniones anteriores, ayudan bastante.😊
